index:
    path: /
    controller: App\Controller\StaticController::index

ajout:
    path: /ajout
    controller: App\Controller\AjoutClientController::index

modif:
    path: /modif/{id}
    controller: App\Controller\AjoutClientController::modifClient

liste_clients:
    path: /liste
    controller: App\Controller\AjoutClientController:listeClients