index:
    path: /
    controller: App\Controller\StaticController::index

ajout:
    path: /ajout
    controller: App\Controller\AjoutClientController::index

modif:
    path: /modif
    controller: App\Controller\AjoutClientController::modifClient

liste:
    path: /liste
    controller: App\Controller\AjoutClientController:listeClients